[tool.black]
line-length = 79
preview = true

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::sqlalchemy.exc.SADeprecationWarning",
    "ignore::sqlalchemy.exc.SAWarning",
    "ignore::DeprecationWarning"
]
addopts = "--ckan-ini test.ini"

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
known_third_party = ["pytest"]
known_ckan = ["ckan"]
known_ckanext = ["ckanext"]
known_datavic = ["ckanext.datavicmain"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "CKAN", "CKANEXT", "DATAVIC", "LOCALFOLDER"]
