scheming_version: 2
schema_id: datavicmain_home_item
about: A form for an item in the home page

fields:
  - field_name: title
    label: Title
    required: true
    form_attrs:
      required: 1

  - field_name: description
    label: Description

  - field_name: file
    label: File
    preset: resource_url_upload

  - field_name: section_type
    label: Type
    preset: select
    required: true
    choices:
      - value: news
        label: News or Event
      - value: data
        label: Data Category
      - value: resources
        label: Resource
    form_attrs:
      required: 1

  - field_name: state
    label: State
    preset: select
    required: true
    choices:
      - value: active
        label: Active
      - value: inactive
        label: Inactive
    form_attrs:
      required: 1

  - field_name: weight
    label: Weight
    form_snippet: vic_text.html
    input_type: numeric
    validators: default(0) int_validator
