version: 1
groups:
  - annotation: ckanext-datavicmain
    options:
      - key: ckan.pages.show_blog_button
        type: bool
        default: True

      - key: ckan.pages.base_url
        default: pages

      - key: ckanext.datavicmain.data_request.contact_email
        default: datavic@dpc.vic.gov.au
